import { makeStyles } from '@mui/styles';

const useStyles = makeStyles((theme) => ({
  container: {
    display: 'flex',
    alignItems: 'center',
    margin: '16px',
    height: '186px',
    padding: '12px',
    objectFit: 'contain',
    borderRadius: '12px',
    boxShadow: '0 6px 10px 0 rgba(131, 134, 163, 0.12)',
    backgroundColor: '#242833',
  },
  top_left: {
    height: '24px',
    margin: '0 70px 12px 4px',
    fontFamily: 'Gilroy',
    fontSize: '20px',
    fontWeight: '400',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: '0.5px',
    color: '#fff',
  },
  top_right: {
    height: '28px',
    margin: '0 1px 8px 29px',
    fontFamily: 'Gilroy',
    fontSize: '12px',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: '0.3px',
    color: '#c7c7cc',
  },
  
  center_price: {
    height: '36px',
    fontFamily: 'Gilroy',
    margin: '8px 29px 0px 4px',
    fontSize: '30px',
    fontWeight: 'bold',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: '0.75px',
    color: '#00c7be',
  },
  setting: {
    width: '32px',
    height: '32px',
  },
  toman_word_center: {
    marginLeft: '5px',
    fontSize: '14px',
    letterSpacing: '0.35px',
  },
  line: {
    width: '100%',
    margin: '12px 0',
    height: '1px',
    border: 'solid 1px #2e374d',
  },
  withdrawal_limit: {
    height: '24px',
    margin: '0px 31px 0px 4px',
    fontFamily: 'Gilroy',
    fontSize: '20px',
    fontWeight: 'bold',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 'normal',
    letterSpacing: '0.5px',
    color: '#fff',
  },
  bottom_price: {
    height: '29px',
    margin: ' 12px 0px 0 4px',
    fontFamily: 'Gilroy',
    fontSize: ' 24px',
    fontWeight: 'bold',
    fontStretch: 'normal',
    fontStyle: ' normal',
    lineHeight: 'normal',
    letterSpacing: '0.6px',
    color: '#fff',
  },

  toman_word_bottom: {
    marginLeft: '5px',
    fontSize: '14px',
    letterSpacing: ' 0.35px',
    fontFamily: 'Gilroy',
  },
  btn_withdrawal: {
    width: ' 114px',
    height: '32px',
    margin: '9px 4px 0 16px',
    padding: '3px 0',
    borderRadius: '8px',
    boxShadow: '0 6px 10px 0 rgba(53, 130, 255, 0.24)',
    backgroundColor: '#007aff',
    fontFamily: 'Gilroy',
    fontSize: '16px',
    fontWeight: 'bold',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: '1.63',
    letterSpacing: 'normal',
    textAlign: 'center',
    color: '#fff',
  },
}));

export default useStyles;
